Update index.js
LeeviHalme/node-steam-openid pull request #24
Opened 2024-11-16 03:34 UTC by sapsanDev

Add animated avatar and frame

2024-11-18 21:18 UTC, LeeviHalme requested changes
Thanks @sapsanDev for the new feature PR! Highly appreciated!

Requested changes for few nits that could be corrected to keep consistency, but other than that LGMT :)

2024-11-18 21:18 UTC, LeeviHalme commented on index.js
> +        {
Nit: The brace style here doesn't match the rest of the codebase. Use `if (condition) { ... }` to keep it consistent.

```suggestion
        if (players && players.length > 0) {
```

2024-11-18 21:18 UTC, LeeviHalme commented on index.js
> +            AvatarFrame.data.response.avatar_frame;
Nit: Variable naming uses `camelCase` style elsewhere.

```suggestion
          const animatedAvatar = await axios.get(
            `https://api.steampowered.com/IPlayerService/GetAnimatedAvatar/v1/?key=${this.apiKey}&steamid=${steamId}`
          );

          const animated = 
            animatedAvatar.data &&
            animatedAvatar.data.response &&
            animatedAvatar.data.response.avatar;

          const avatarFrame = await axios.get(
            `https://api.steampowered.com/IPlayerService/GetAvatarFrame/v1/?key=${this.apiKey}&steamid=${steamId}`
          );

          const frame =
            avatarFrame.data &&
            avatarFrame.data.response &&
            avatarFrame.data.response.avatar_frame;

```

2024-11-18 21:18 UTC, LeeviHalme commented on index.js
> +            {
Same with the brace style here.

```suggestion
            avatar: {
```

2024-11-18 21:18 UTC, LeeviHalme commented on index.js
> +              frame: Frame.image_small ? `https://cdn.akamai.steamstatic.com/steamcommunity/public/images/${Frame.image_small}` : null
Add safe accessing to the object.

```suggestion
              large: player.avatarfull,
              animated: animated?.image_small ? `https://cdn.akamai.steamstatic.com/steamcommunity/public/images/${Animated.image_small}`: player.avatarfull,
              frame: frame?.image_small ? `https://cdn.akamai.steamstatic.com/steamcommunity/public/images/${Frame.image_small}` : null
```

2024-11-19 09:54 UTC, sapsanDev commented on index.js
> +              frame: Frame.image_small ? `https://cdn.akamai.steamstatic.com/steamcommunity/public/images/${Frame.image_small}` : null
Ok, ready.

2024-11-22 01:10 UTC, LeeviHalme approved these changes
Thanks! I've made a few commits myself for small style changes.

I've left out the `d.ts` file from this merge, but feel free to open another PR for the package providing its own types.

2024-11-22 01:11 UTC, merged